steps:
  # Step 1: Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/groceryshopperai:latest",
        "."
      ]

  # Step 2: Push Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/groceryshopperai:latest"
      ]

  # Step 3: Deploy to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "run",
        "deploy",
        "groceryshopperai",
        "--image",
        "us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/groceryshopperai:latest",
        "--region",
        "us-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated"
      ]

images:
  - "us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/groceryshopperai:latest"
